"""BODS v0.4 mapping, validation, and helpers.

Every source adapter in OpenCheck feeds through this package before
anything user-facing happens. The design principle is that BODS v0.4
is the internal spine, not an export format — so the UI, risk rules,
and (later) export adapters all work off the mapped statements, not
the raw source payloads.
"""

from .mapper import (
    BODSBundle,
    make_entity_statement,
    make_person_statement,
    make_relationship_statement,
    map_abr_australia,
    map_acra_singapore,
    map_ariregister,
    map_cvr_denmark,
    map_ares,
    map_bce_belgium,
    map_corporations_canada,
    map_cyprus_drcor,
    map_bolagsverket,
    map_bods_gleif,
    map_bods_uk_psc,
    map_brreg,
    map_climatetrace,
    map_cnpj_brazil,
    map_companies_house,
    map_cro,
    map_everypolitician,
    map_firmenbuch,
    map_ftm,
    map_gleif,
    map_gleif_subsidiaries,
    map_inpi,
    map_kvk,
    map_malta_mbr,
    map_nz_companies,
    map_openaleph,
    map_opencorporates,
    map_opensanctions,
    map_opentender,
    map_prh,
    map_jar_lithuania,
    map_krs_poland,
    map_rpo_slovakia,
    map_rpvs_slovakia,
    map_sec_edgar,
    map_sudreg_croatia,
    map_ur_latvia,
    map_wikidata,
    map_zefix,
)
from .senzing import map_to_senzing, to_senzing_jsonl
from .neo4j import to_cypher
from .validator import validate_shape, ValidationError

__all__ = [
    "BODSBundle",
    "make_entity_statement",
    "make_person_statement",
    "make_relationship_statement",
    "map_abr_australia",
    "map_acra_singapore",
    "map_ariregister",
    "map_cvr_denmark",
    "map_ares",
    "map_bce_belgium",
    "map_bolagsverket",
    "map_corporations_canada",
    "map_cyprus_drcor",
    "map_bods_gleif",
    "map_bods_uk_psc",
    "map_brreg",
    "map_climatetrace",
    "map_cnpj_brazil",
    "map_companies_house",
    "map_cro",
    "map_everypolitician",
    "map_firmenbuch",
    "map_ftm",
    "map_gleif",
    "map_inpi",
    "map_kvk",
    "map_malta_mbr",
    "map_nz_companies",
    "map_opencorporates",
    "map_opensanctions",
    "map_openaleph",
    "map_opentender",
    "map_prh",
    "map_jar_lithuania",
    "map_krs_poland",
    "map_rpo_slovakia",
    "map_rpvs_slovakia",
    "map_sec_edgar",
    "map_sudreg_croatia",
    "map_ur_latvia",
    "map_wikidata",
    "map_zefix",
    "map_to_senzing",
    "to_senzing_jsonl",
    "to_cypher",
    "validate_shape",
    "ValidationError",
]
