"""What is knowable about a company in a given jurisdiction — Phase 223.

"10 of 10 sources answered" is true and misleading at once: it says nothing
about what those ten *could* have told us. A British report should say that
the PSC register is public but bands holdings at 25/50/75 % and stops at the
first qualifying link; a Danish one that CVR publishes officers publicly but
beneficial owners only on legitimate interest, through a register OpenCheck
does not read; a Cayman one that no Cayman register is read at all, so an
absent owner is a fact about coverage and not about the company.

This module is the **jurisdiction-keyed** layer that says so. It is distinct
from, and composes with, the two source-keyed registries that already exist:

* ``bods/bo_regimes.py`` — per *source*, the legal definition behind the
  ``beneficialOwnershipOrControl`` flag (threshold wording, record kinds);
* ``bo_access.py`` — the per-register footnote on the source card, which
  since this phase is a thin view over the data held here.

**The data is Stephen's, not the code's.** ``data/jurisdictions.json`` is
generated by ``scripts/sync_jurisdictions.py`` from the Notion database
"Beneficial ownership access status", which he keeps current; nothing in
this file hand-types a legal fact. A row he has not stamped with a
*Last verified* date is carried with ``review_status: "unverified"`` and
the generated ``docs/knowability.md`` says so beside it. Validation is at
import and fail-fast (a bad code, date or enum value stops the process and
CI), the ``bo_access`` pattern.

Three rules the sentence keeps, and the tests pin:

1. **It describes and dates; it never judges.** "Accessible to authorities
   and obliged entities, and to others on legitimate interest, since 1 Sept
   2025" is a fact; "opaque" is the reader's conclusion. ``BANNED_VOCABULARY``
   lists the words that would turn a register fact into a risk claim, and ``test_knowability.py`` fails the
   build on any of them. Nothing here feeds ``risk.py``: a jurisdiction-level
   "no register" *signal* was rejected in the AMLA geographic-risk work
   (Aug 2026) because "we found nothing" conflates *no register* / *closed
   register* / *no adapter yet* and turns a coverage gap into an accusation.
   This statement is the honest place to make exactly that three-way
   distinction, as a dated fact.
2. **Absence is stated in the same voice as presence.** A jurisdiction with
   no entry gets a sentence saying so (``stated_absence``), never silence —
   silence reads as "nothing to see".
3. **What OpenCheck reads is derived, never typed.** ``opencheck_reads`` is
   computed from the adapter REGISTRY at import (``SourceInfo.country``), so
   it cannot drift from what the lookup actually dispatches. That is what
   separates *the register does not publish it* from *OpenCheck does not
   read it*.
"""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

from .findings import clauses_to_sentence

_DATA_PATH = Path(__file__).parent / "data" / "jurisdictions.json"

#: The access enum — the one decided on the knowability ticket (18 Sept 2026),
#: replacing ``bo_access``'s date-only model which could not say "public",
#: "public with a justification step" or "restricted, no legitimate-interest
#: route yet".
#:
#: It is a **ladder, one value per row**: the widest tier of access that
#: works today, beyond the AMLD floor every EU/EEA register has (competent
#: authorities and obliged entities). The Notion column's description and the
#: database description carry the same definitions, agreed 18 Sept 2026:
#:
#: * ``public`` — anyone, no registration or reason.
#: * ``public_with_registration_or_justification`` — anyone, after an
#:   account, fee or stated purpose; no legitimate-interest test.
#: * ``legitimate_interest`` — authorities and obliged entities, plus others
#:   on legitimate interest through a route that works today
#:   (``access_since`` = when it opened).
#: * ``restricted_no_lia_route_yet`` — legitimate-interest access is in force
#:   in law but no operational application route exists yet (Sweden).
#: * ``authorities_and_obliged_entities_only`` — the floor only; LIA not in
#:   force: not legislated, or legislated but not commenced (a known
#:   commencement date goes in ``next_change_expected`` — Ireland; a draft
#:   with no date is described in ``pending_changes`` — Italy).
#: * ``no_register`` / ``in_progress`` — nothing to consult, yet or at all.
#:
#: ``amld6_lia`` records the *legal* position; ``access`` records *practice*.
#: Transitions are never a second value — they are ``access_since``,
#: ``next_change_expected`` and ``pending_changes``.
AccessStatus = Literal[
    "public",
    "public_with_registration_or_justification",
    "legitimate_interest",
    "restricted_no_lia_route_yet",
    "authorities_and_obliged_entities_only",
    "no_register",
    "in_progress",
]

ACCESS_STATUSES: tuple[str, ...] = (
    "public",
    "public_with_registration_or_justification",
    "legitimate_interest",
    "restricted_no_lia_route_yet",
    "authorities_and_obliged_entities_only",
    "no_register",
    "in_progress",
)

#: Words that would turn a register fact into a judgement. The sentence
#: describes what a jurisdiction publishes; whether that is a problem is the
#: analyst's call (``verdict.py`` keeps the same rule).
BANNED_VOCABULARY: tuple[str, ...] = (
    "opaque",
    "opacity",
    "secrecy",
    "secretive",
    "haven",
    "hidden",
    "hide",
    "shell",
    "risk",
    "risky",
    "suspicious",
    "launder",
    "evasion",
    "loophole",
)

_EU_EEA: frozenset[str] = frozenset(
    "AT BE BG HR CY CZ DK EE FI FR DE GR HU IE IT LV LT LU MT NL PL PT RO SK SI ES SE "
    "IS LI NO".split()
)


class Source(BaseModel):
    url: str
    title: str | None = None

    @field_validator("url")
    @classmethod
    def _url_shape(cls, v: str) -> str:
        v = v.strip()
        if not v.startswith(("http://", "https://")):
            raise ValueError(f"source url must be http(s): {v!r}")
        return v


class BoRegister(BaseModel):
    """The beneficial ownership register, as Stephen recorded it."""

    name: str | None = None
    url: str | None = None
    access: AccessStatus | None = Field(
        default=None,
        description="None = not yet recorded; the sentence says so rather than guessing.",
    )
    access_since: date | None = None
    next_change_expected: date | None = None
    access_url: str | None = Field(
        default=None,
        description="Where to learn how to apply for access (the first source URL).",
    )
    threshold_wording: str | None = None
    fields_published: list[str] = Field(default_factory=list)
    reporting_basis: Literal["first_qualifying_link", "ultimate_natural_person", "unknown"] | None = None
    covers: list[str] = Field(default_factory=list)
    verification: Literal[
        "self_declared", "identity_verified", "cross_checked_against_registers", "unknown"
    ] | None = None
    verification_note: str | None = None
    amld6_lia: Literal["Yes", "No", "Not applicable"] | None = None
    amld6_details: str | None = None
    boris: Literal["Yes", "No", "Not applicable"] | None = None
    amlr_alignment_watch: bool = False
    pending_changes: str | None = None

    @field_validator("url", "access_url")
    @classmethod
    def _url_shape(cls, v: str | None) -> str | None:
        if v is None:
            return None
        v = v.strip()
        if v and not v.startswith(("http://", "https://")):
            raise ValueError(f"url must be http(s): {v!r}")
        return v or None


class CompanyRegister(BaseModel):
    name: str | None = None
    url: str | None = None
    publishes: list[str] = Field(default_factory=list)
    public: Literal["Yes", "Partly", "No"] | None = None


class FatfAssessment(BaseModel):
    body: str | None = None
    onsite: date | None = None
    plenary: date | None = None


class Jurisdiction(BaseModel):
    """One row of the Notion table, validated."""

    code: str
    name: str
    groups: list[str] = Field(default_factory=list)
    bo_register: BoRegister = Field(default_factory=BoRegister)
    company_register: CompanyRegister = Field(default_factory=CompanyRegister)
    fatf: FatfAssessment = Field(default_factory=FatfAssessment)
    opencheck_source_note: str | None = Field(
        default=None,
        description="Stephen's free-text note on adapters; the derived list is authoritative.",
    )
    sources: list[Source] = Field(default_factory=list)
    notes: str | None = None
    last_verified: date | None = None
    notion_page_id: str | None = None

    @field_validator("code")
    @classmethod
    def _code_shape(cls, v: str) -> str:
        v = v.strip().upper()
        if not re.fullmatch(r"[A-Z]{2}(-[A-Z0-9]{1,3})?", v):
            raise ValueError(f"jurisdiction code must be ISO 3166-1 alpha-2 (or US-XX): {v!r}")
        return v

    @property
    def review_status(self) -> Literal["verified", "unverified"]:
        return "verified" if self.last_verified else "unverified"

    @property
    def eu_eea(self) -> bool:
        return self.code in _EU_EEA


class SourceRead(BaseModel):
    """One adapter that reads this jurisdiction — derived, never typed."""

    source_id: str
    name: str
    requires_api_key: bool
    reads_beneficial_owners: bool


class KnowabilityStatement(BaseModel):
    """What the reader gets: the sentence, and every field behind it."""

    code: str
    name: str
    sentence: str
    sentences: list[str]
    stated_absence: bool
    review_status: Literal["verified", "unverified", "absent"]
    last_verified: str | None = None
    access: str | None = None
    access_since: str | None = None
    next_change_expected: str | None = None
    fields: dict[str, Any] = Field(default_factory=dict)
    opencheck_reads: list[SourceRead] = Field(default_factory=list)
    sources: list[Source] = Field(default_factory=list)


# ----------------------------------------------------------------------
# Loading
# ----------------------------------------------------------------------
def _load(path: Path = _DATA_PATH) -> dict[str, Jurisdiction]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    rows = raw["jurisdictions"] if isinstance(raw, dict) else raw
    out: dict[str, Jurisdiction] = {}
    for payload in rows:
        j = Jurisdiction.model_validate(payload)
        if j.code in out:
            raise ValueError(f"jurisdictions.json: duplicate code {j.code}")
        out[j.code] = j
    return out


def _generated_at(path: Path = _DATA_PATH) -> str | None:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return raw.get("generated_at") if isinstance(raw, dict) else None


#: Validated at import — a malformed row fails the process (and CI) loudly.
JURISDICTIONS: dict[str, Jurisdiction] = _load()
GENERATED_AT: str | None = _generated_at()


def get_jurisdiction(code: str | None) -> Jurisdiction | None:
    if not code:
        return None
    cc = code.strip().upper()
    if cc in JURISDICTIONS:
        return JURISDICTIONS[cc]
    # ``US-DE`` falls back to ``US`` when no state row exists.
    return JURISDICTIONS.get(cc.split("-")[0])


# ----------------------------------------------------------------------
# What OpenCheck reads — derived from the adapter registry
# ----------------------------------------------------------------------
def opencheck_reads(code: str) -> list[SourceRead]:
    """Every registered adapter whose ``SourceInfo.country`` is *code*.

    ``reads_beneficial_owners`` is true when ``bo_regimes`` records at least
    one record kind the adapter asserts as a beneficial ownership declaration
    — the only ground on which the sentence may say that OpenCheck reads
    beneficial owners rather than officers or shareholders.
    """
    from .bods.bo_regimes import REGIMES
    from .sources import REGISTRY

    cc = code.strip().upper().split("-")[0]
    out: list[SourceRead] = []
    for source_id, adapter in REGISTRY.items():
        info = adapter.info
        if (info.country or "").upper() != cc:
            continue
        regime = REGIMES.get(source_id)
        reads_bo = bool(regime) and any(
            policy == "assert_true" for policy in regime.record_kinds.values()
        )
        out.append(
            SourceRead(
                source_id=source_id,
                name=info.name,
                requires_api_key=bool(info.requires_api_key),
                reads_beneficial_owners=reads_bo,
            )
        )
    return sorted(out, key=lambda s: s.source_id)


# ----------------------------------------------------------------------
# The sentence
# ----------------------------------------------------------------------
def _fmt_date(d: date | None) -> str | None:
    if d is None:
        return None
    return f"{d.day} {d.strftime('%b')} {d.year}"


def _register_name(j: Jurisdiction) -> str:
    return j.bo_register.name or f"{j.name}'s beneficial ownership register"


def _access_sentences(j: Jurisdiction, today: date) -> list[str]:
    """Sentence 1 (and, for one rung, 2): who can see beneficial owners, dated.

    A list so a rung that needs two facts can spend two sentences instead of
    losing the second clause to the 140-character cap."""
    r = j.bo_register
    reg = _register_name(j)
    since = _fmt_date(r.access_since)
    nxt = _fmt_date(r.next_change_expected)
    upcoming = (
        f"a change is announced for {nxt}"
        if r.next_change_expected and r.next_change_expected > today
        else None
    )
    if r.access is None:
        return [
            clauses_to_sentence(
                [f"who may look up the beneficial owners of companies in {j.name} is not yet recorded here"],
                sep="; ",
            )
        ]
    if r.access == "public":
        head = f"{reg} is open to the public"
        if since:
            head += f" (current arrangement since {since})"
        return [clauses_to_sentence([head, upcoming], sep="; ")]
    if r.access == "public_with_registration_or_justification":
        head = f"{reg} is open to the public after registration or a stated reason"
        if since:
            head += f", since {since}"
        return [clauses_to_sentence([head, upcoming], sep="; ")]
    if r.access == "legitimate_interest":
        # The ladder (agreed with Stephen, 18 Sept 2026): every tier below
        # "public" includes the AMLD floor — authorities and obliged entities —
        # and the sentence says so, so a reader does not take "legitimate
        # interest" to mean banks are locked out too.
        head = (
            f"{reg} is accessible to authorities and obliged entities, "
            "and to others on legitimate interest"
        )
        if since:
            head += f", since {since}"
        return [clauses_to_sentence([head, upcoming], sep="; ")]
    if r.access == "restricted_no_lia_route_yet":
        # Sweden's shape. Two sentences: the second fact is too long to
        # survive the cap behind a register name and a date.
        head = f"{reg} is accessible to authorities and obliged entities"
        if since:
            head += f", since {since}"
        return [
            clauses_to_sentence([head, upcoming], sep="; "),
            clauses_to_sentence(
                ["a legitimate-interest route is provided for in law but is not yet open"], sep="; "
            ),
        ]
    if r.access == "authorities_and_obliged_entities_only":
        head = f"{reg} is open to authorities and obliged entities only"
        if since:
            head += f", since {since}"
        return [clauses_to_sentence([head, upcoming], sep="; ")]
    if r.access == "no_register":
        return [
            clauses_to_sentence(
                [f"{j.name} keeps no central register of beneficial owners", upcoming], sep="; "
            )
        ]
    if r.access == "in_progress":
        return [
            clauses_to_sentence(
                [f"{j.name}'s register of beneficial owners is being set up and is not yet open", upcoming],
                sep="; ",
            )
        ]
    return []


def _recorded_sentences(j: Jurisdiction) -> list[str]:
    """Sentence 2 (and 3): what a reader with access actually sees, then how
    it is checked. Two sentences, not one, so the 140-character cap that
    every ``clauses_to_sentence`` call enforces cannot drop the verification
    clause behind a long threshold."""
    r = j.bo_register
    if r.access in ("no_register", None):
        return []
    out: list[str] = []
    parts: list[str | None] = []
    if r.threshold_wording:
        parts.append(f"it records holders of {r.threshold_wording}")
    if "exact_holdings" in r.fields_published:
        parts.append("as exact holdings")
    elif "percentage_bands" in r.fields_published:
        parts.append("in percentage bands")
    elif "nothing" in r.fields_published:
        parts.append("publishing nothing to the reader")
    if r.reporting_basis == "first_qualifying_link":
        parts.append("at the first qualifying link rather than the ultimate person")
    elif r.reporting_basis == "ultimate_natural_person":
        parts.append("down to the ultimate natural person")
    recorded = clauses_to_sentence(parts, sep=", ")
    if recorded:
        out.append(recorded)
    verification = {
        "identity_verified": "identities are verified but the holdings claimed are not",
        "cross_checked_against_registers": "filings are cross-checked against other registers",
        "self_declared": "filings are self-declared and not checked",
    }.get(r.verification or "")
    if verification:
        checked = clauses_to_sentence([verification], sep=", ")
        if checked:
            out.append(checked)
    return out


def _reads_sentence(j: Jurisdiction, reads: list[SourceRead]) -> str | None:
    """Sentence 3: what OpenCheck reads of it — the honest coverage line."""
    if not reads:
        return clauses_to_sentence(
            [
                f"OpenCheck reads no {j.name} register",
                f"so an owner absent from this report says nothing about what {j.name} holds",
            ],
            sep=", ",
        )
    bo = [s for s in reads if s.reads_beneficial_owners]
    if bo:
        head = f"OpenCheck reads beneficial owners from {', '.join(s.name for s in bo[:2])}"
        return clauses_to_sentence([head], sep=", ")
    names = ", ".join(s.name for s in reads[:3])
    return clauses_to_sentence(
        [f"OpenCheck reads {names}", "for officers and registered holdings, not beneficial owners"],
        sep=" ",
    )


def statement_for(code: str | None, today: date | None = None) -> KnowabilityStatement:
    """The statement for *code* — always a statement, never ``None``.

    An unknown code gets the stated-absence sentence; a known code gets two
    or three sentences, each built with ``clauses_to_sentence`` so a missing
    field shortens the sentence rather than producing "since None".
    """
    today = today or date.today()
    cc = (code or "").strip().upper() or "??"
    j = get_jurisdiction(cc)
    if j is None:
        name = _country_name(cc)
        sentence = clauses_to_sentence(
            [
                f"OpenCheck holds no register notes for {name}",
                f"an owner absent from this report says nothing about what {name} publishes",
            ],
            sep="; ",
        ) or ""
        return KnowabilityStatement(
            code=cc,
            name=name,
            sentence=sentence,
            sentences=[sentence],
            stated_absence=True,
            review_status="absent",
        )
    reads = opencheck_reads(j.code)
    sentences = [
        s
        for s in (
            *_access_sentences(j, today),
            *_recorded_sentences(j),
            _reads_sentence(j, reads),
        )
        if s
    ]
    r = j.bo_register
    return KnowabilityStatement(
        code=j.code,
        name=j.name,
        sentence=" ".join(sentences),
        sentences=sentences,
        stated_absence=False,
        review_status=j.review_status,
        last_verified=j.last_verified.isoformat() if j.last_verified else None,
        access=r.access,
        access_since=r.access_since.isoformat() if r.access_since else None,
        next_change_expected=(
            r.next_change_expected.isoformat() if r.next_change_expected else None
        ),
        fields={
            "register": r.name,
            "register_url": r.url,
            "threshold_wording": r.threshold_wording,
            "fields_published": list(r.fields_published),
            "reporting_basis": r.reporting_basis,
            "covers": list(r.covers),
            "verification": r.verification,
            "verification_note": r.verification_note,
            "amld6_lia": r.amld6_lia,
            "amld6_details": r.amld6_details,
            "boris": r.boris,
            "amlr_alignment_watch": r.amlr_alignment_watch,
            "pending_changes": r.pending_changes,
            "company_register": j.company_register.model_dump(),
            "fatf": {
                "body": j.fatf.body,
                "onsite": j.fatf.onsite.isoformat() if j.fatf.onsite else None,
                "plenary": j.fatf.plenary.isoformat() if j.fatf.plenary else None,
            },
            "eu_eea": j.eu_eea,
            "groups": list(j.groups),
            "notes": j.notes,
        },
        opencheck_reads=reads,
        sources=list(j.sources),
    )


def statements_for(codes: list[str], today: date | None = None) -> list[KnowabilityStatement]:
    """One statement per distinct code, in the order first seen."""
    seen: list[str] = []
    for c in codes:
        cc = (c or "").strip().upper()
        if cc and cc not in seen:
            seen.append(cc)
    return [statement_for(c, today) for c in seen]


def _country_name(code: str) -> str:
    try:
        import pycountry  # type: ignore

        rec = pycountry.countries.get(alpha_2=code.split("-")[0])
        if rec is not None:
            return getattr(rec, "common_name", None) or rec.name
    except Exception:  # pragma: no cover - pycountry is optional at this layer
        pass
    return code


# ----------------------------------------------------------------------
# Chain jurisdictions — for FullCheck (Phase C wiring; the helper ships now)
# ----------------------------------------------------------------------
def chain_jurisdictions(bods: list[dict[str, Any]], subject_id: str | None) -> list[str]:
    """The jurisdictions of every *entity* on the upward ownership path from
    the subject, subject first — ended relationships included (Stephen,
    18 Sept 2026: a former owner's jurisdiction still shaped what was
    knowable). Persons carry no jurisdiction and are skipped.
    """
    from .reconcile import _entity_jurisdiction
    from .risk import _statement_id, _stmt_kind, _upstream_entity_ids

    by_id = {_statement_id(s): s for s in bods if _stmt_kind(s) == "entity"}
    if not subject_id or subject_id not in by_id:
        return []
    ordered: list[str] = []

    def _add(stmt: dict[str, Any]) -> None:
        code = _entity_jurisdiction(stmt.get("recordDetails") or {})
        if code and code not in ordered:
            ordered.append(code)

    _add(by_id[subject_id])
    for sid in sorted(_upstream_entity_ids(subject_id, bods)):
        if sid in by_id:
            _add(by_id[sid])
    return ordered
