#!/usr/bin/env python3
"""Render ``docs/knowability.md`` from ``opencheck/data/jurisdictions.json``.

The review artefact for the knowability work (Phase 223): one section per
jurisdiction with the sentence OpenCheck will show, the fields behind it and
Stephen's *Last verified* stamp — so a row he has not checked is visibly an
unverified draft. Regenerate after every ``sync_jurisdictions.py`` run:

    python3 scripts/generate_knowability_doc.py            # write
    python3 scripts/generate_knowability_doc.py --check    # CI: fail on drift

Everything on the page is derived; edit the Notion table, not this file.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from opencheck.knowability import (  # noqa: E402
    ACCESS_STATUSES,
    GENERATED_AT,
    JURISDICTIONS,
    statement_for,
)

OUT_PATH = Path(__file__).resolve().parents[2] / "docs" / "knowability.md"

#: The sentences are dated, so the page is rendered "as of" a fixed day —
#: the day the data was generated — not the day the script happens to run.
#: That keeps ``--check`` stable between the sync and the CI run.
def _as_of() -> date:
    if GENERATED_AT:
        return date.fromisoformat(GENERATED_AT[:10])
    return date.today()


def _md_escape(s: str | None) -> str:
    return (s or "—").replace("|", "\\|").replace("\n", " ")


def render() -> str:
    today = _as_of()
    rows = sorted(JURISDICTIONS.values(), key=lambda j: (j.name.lower()))
    verified = [j for j in rows if j.last_verified]
    unverified = [j for j in rows if not j.last_verified]
    by_status: dict[str, int] = {s: 0 for s in ACCESS_STATUSES}
    unrecorded = 0
    for j in rows:
        if j.bo_register.access:
            by_status[j.bo_register.access] += 1
        else:
            unrecorded += 1

    out: list[str] = []
    out.append("# What is knowable, per jurisdiction")
    out.append("")
    out.append(
        "<!-- GENERATED by backend/scripts/generate_knowability_doc.py from "
        "backend/opencheck/data/jurisdictions.json — edit the Notion table "
        "\"Beneficial ownership access status\", run sync_jurisdictions.py, then regenerate. -->"
    )
    out.append("")
    out.append(
        "One statement per jurisdiction of what its registers publish about beneficial owners, "
        "who may see it, and what OpenCheck reads of it (Phase 223). The facts are Stephen's, "
        "maintained in the Notion database *Beneficial ownership access status*; the sentence is "
        "generated by `opencheck/knowability.py` and is the one the QuickCheck verdict strip, the "
        "PDF/Markdown report, the MCP `summary` and the entity pages will carry. It describes and "
        "dates; it never judges — see the module docstring for the three rules and the "
        "banned-vocabulary guard."
    )
    out.append("")
    out.append(
        f"Data generated {GENERATED_AT or 'n/a'}; sentences rendered as of {today.isoformat()}. "
        f"**{len(verified)} of {len(rows)} rows verified by Stephen** (a `Last verified` date in the "
        f"table); the other {len(unverified)} are drafts from his trackers and are marked *unverified* below."
    )
    out.append("")
    out.append("## Access status at a glance")
    out.append("")
    out.append("| Access status | Jurisdictions |")
    out.append("|---|---|")
    for s in ACCESS_STATUSES:
        codes = ", ".join(j.code for j in rows if j.bo_register.access == s)
        out.append(f"| `{s}` | {codes or '—'} |")
    if unrecorded:
        codes = ", ".join(j.code for j in rows if not j.bo_register.access)
        out.append(f"| *not yet recorded* | {codes} |")
    out.append("")
    out.append("## Jurisdictions")
    out.append("")
    for j in rows:
        st = statement_for(j.code, today)
        badge = (
            f"verified {j.last_verified.isoformat()}" if j.last_verified else "**unverified draft**"
        )
        out.append(f"### {j.name} ({j.code}) — {badge}")
        out.append("")
        out.append(f"> {st.sentence}")
        out.append("")
        r = j.bo_register
        out.append("| Field | Value |")
        out.append("|---|---|")
        out.append(f"| Groups | {_md_escape(', '.join(j.groups))} |")
        out.append(f"| BO register | {_md_escape(r.name)}{' — ' + r.url if r.url else ''} |")
        out.append(f"| Access | `{r.access}` |" if r.access else "| Access | *not recorded* |")
        out.append(f"| Access since / next change | {r.access_since or '—'} / {r.next_change_expected or '—'} |")
        out.append(f"| Threshold wording | {_md_escape(r.threshold_wording)} |")
        out.append(f"| Fields published | {_md_escape(', '.join(r.fields_published))} |")
        out.append(f"| Reporting basis | {_md_escape(r.reporting_basis)} |")
        out.append(f"| Covers | {_md_escape(', '.join(r.covers))} |")
        out.append(
            f"| Verification | {_md_escape(r.verification)}"
            f"{' — ' + _md_escape(r.verification_note) if r.verification_note else ''} |"
        )
        out.append(f"| 6AMLD LIA / BORIS | {r.amld6_lia or '—'} / {r.boris or '—'} |")
        if r.amld6_details:
            out.append(f"| 6AMLD details | {_md_escape(r.amld6_details)} |")
        if r.amlr_alignment_watch:
            out.append("| AMLR alignment watch | yes — threshold wording must move to \"25 % or more\" by 10 July 2027 |")
        if r.pending_changes:
            out.append(f"| Pending changes | {_md_escape(r.pending_changes)} |")
        c = j.company_register
        if c.name or c.url or c.publishes or c.public:
            out.append(
                f"| Company register | {_md_escape(c.name)}{' — ' + c.url if c.url else ''}; "
                f"public: {c.public or '—'}; publishes: {_md_escape(', '.join(c.publishes))} |"
            )
        f = j.fatf
        if f.body or f.onsite or f.plenary:
            out.append(
                f"| Next FATF/FSRB assessment | {_md_escape(f.body)}; onsite {f.onsite or '—'}; "
                f"plenary {f.plenary or '—'} |"
            )
        reads = st.opencheck_reads
        if reads:
            out.append(
                "| OpenCheck reads | "
                + ", ".join(
                    f"`{s.source_id}`{' (BO)' if s.reads_beneficial_owners else ''}"
                    f"{' (API key)' if s.requires_api_key else ''}"
                    for s in reads
                )
                + " |"
            )
        else:
            out.append("| OpenCheck reads | *no adapter for this jurisdiction* |")
        if j.opencheck_source_note:
            out.append(f"| OpenCheck source (note) | {_md_escape(j.opencheck_source_note)} |")
        if j.sources:
            out.append("| Sources | " + " · ".join(s.url for s in j.sources) + " |")
        if j.notes:
            out.append(f"| Notes | {_md_escape(j.notes)} |")
        out.append("")
    out.append("## Stated absence")
    out.append("")
    absent = statement_for("XX", today)
    out.append(
        "A jurisdiction with no row gets a sentence, never silence — the fallback reads, for a code "
        f"the table does not hold: *{absent.sentence.replace('XX', 'Ruritania')}*"
    )
    out.append("")
    return "\n".join(out)


def _strip_dates(text: str) -> str:
    return re.sub(r"Data generated .*? rendered as of \S+\.", "", text)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", type=Path, default=OUT_PATH)
    args = ap.parse_args(argv)
    text = render()
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if _strip_dates(current) != _strip_dates(text):
            print(f"{args.out} is out of date — run generate_knowability_doc.py", file=sys.stderr)
            return 1
        print(f"{args.out} is in sync")
        return 0
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
