"""EDGAR state and country codes → ISO 3166-1 alpha-2 (Phase 259).

EDGAR marks where a Schedule 13D/13G reporting person is a citizen of, or
organised in (``citizenshipOrOrganization``), with its own two-character
codes: the US states as themselves, everything else as a letter-digit pair —
``X0`` United Kingdom, ``X1`` United States, ``A6`` Ontario. Before Phase 259
the adapter knew only ``X1``, the states, and ``X2`` — which it read as Canada.
**``X2`` is Burkina Faso**; Canada is ``Z4`` (federal) and ``A0``–``B0`` for
the provinces.

Transcribed from the SEC's published table,
https://www.sec.gov/submit-filings/filer-support-resources/edgar-state-country-codes
(fetched 28 Sept 2026; a verbatim copy of its code/name pairs is
``tests/fixtures/sec_edgar/edgar_state_country_codes.json``, and
``tests/test_sec_edgar_phase259.py`` fails if a code here is missing from it,
or a name differs). The ISO code was assigned from the SEC's name with
pycountry and checked by hand where the name is an old one (Swaziland, Turkey,
Cape Verde, Macedonia).

- A US state, DC → ``US``. Guam, Puerto Rico and the US Virgin Islands keep
  their own ISO codes (``GU``, ``PR``, ``VI``), as ISO 3166-1 gives them.
- A Canadian province → ``CA``.
- ``P8`` Netherlands Antilles (dissolved 2010, no current ISO code) and ``XX``
  Unknown → ``""``: the name is carried alone, never a stand-in code.
"""

from __future__ import annotations

#: EDGAR code → (ISO 3166-1 alpha-2 or "", the SEC's name).
EDGAR_CODES: dict[str, tuple[str, str]] = {
    'AL': ('US', 'ALABAMA'),
    'AK': ('US', 'ALASKA'),
    'AZ': ('US', 'ARIZONA'),
    'AR': ('US', 'ARKANSAS'),
    'CA': ('US', 'CALIFORNIA'),
    'CO': ('US', 'COLORADO'),
    'CT': ('US', 'CONNECTICUT'),
    'DE': ('US', 'DELAWARE'),
    'DC': ('US', 'DISTRICT OF COLUMBIA'),
    'FL': ('US', 'FLORIDA'),
    'GA': ('US', 'GEORGIA'),
    'HI': ('US', 'HAWAII'),
    'ID': ('US', 'IDAHO'),
    'IL': ('US', 'ILLINOIS'),
    'IN': ('US', 'INDIANA'),
    'IA': ('US', 'IOWA'),
    'KS': ('US', 'KANSAS'),
    'KY': ('US', 'KENTUCKY'),
    'LA': ('US', 'LOUISIANA'),
    'ME': ('US', 'MAINE'),
    'MD': ('US', 'MARYLAND'),
    'MA': ('US', 'MASSACHUSETTS'),
    'MI': ('US', 'MICHIGAN'),
    'MN': ('US', 'MINNESOTA'),
    'MS': ('US', 'MISSISSIPPI'),
    'MO': ('US', 'MISSOURI'),
    'MT': ('US', 'MONTANA'),
    'NE': ('US', 'NEBRASKA'),
    'NV': ('US', 'NEVADA'),
    'NH': ('US', 'NEW HAMPSHIRE'),
    'NJ': ('US', 'NEW JERSEY'),
    'NM': ('US', 'NEW MEXICO'),
    'NY': ('US', 'NEW YORK'),
    'NC': ('US', 'NORTH CAROLINA'),
    'ND': ('US', 'NORTH DAKOTA'),
    'OH': ('US', 'OHIO'),
    'OK': ('US', 'OKLAHOMA'),
    'OR': ('US', 'OREGON'),
    'PA': ('US', 'PENNSYLVANIA'),
    'RI': ('US', 'RHODE ISLAND'),
    'SC': ('US', 'SOUTH CAROLINA'),
    'SD': ('US', 'SOUTH DAKOTA'),
    'TN': ('US', 'TENNESSEE'),
    'TX': ('US', 'TEXAS'),
    'X1': ('US', 'UNITED STATES'),
    'UT': ('US', 'UTAH'),
    'VT': ('US', 'VERMONT'),
    'VA': ('US', 'VIRGINIA'),
    'WA': ('US', 'WASHINGTON'),
    'WV': ('US', 'WEST VIRGINIA'),
    'WI': ('US', 'WISCONSIN'),
    'WY': ('US', 'WYOMING'),
    'A0': ('CA', 'ALBERTA, CANADA'),
    'A1': ('CA', 'BRITISH COLUMBIA, CANADA'),
    'A2': ('CA', 'MANITOBA, CANADA'),
    'A3': ('CA', 'NEW BRUNSWICK, CANADA'),
    'A4': ('CA', 'NEWFOUNDLAND, CANADA'),
    'A5': ('CA', 'NOVA SCOTIA, CANADA'),
    'A6': ('CA', 'ONTARIO, CANADA'),
    'A7': ('CA', 'PRINCE EDWARD ISLAND, CANADA'),
    'A8': ('CA', 'QUEBEC, CANADA'),
    'A9': ('CA', 'SASKATCHEWAN, CANADA'),
    'B0': ('CA', 'YUKON, CANADA'),
    'Z4': ('CA', 'CANADA (Federal Level)'),
    'B2': ('AF', 'AFGHANISTAN'),
    'Y6': ('AX', 'ALAND ISLANDS'),
    'B3': ('AL', 'ALBANIA'),
    'B4': ('DZ', 'ALGERIA'),
    'B5': ('AS', 'AMERICAN SAMOA'),
    'B6': ('AD', 'ANDORRA'),
    'B7': ('AO', 'ANGOLA'),
    '1A': ('AI', 'ANGUILLA'),
    'B8': ('AQ', 'ANTARCTICA'),
    'B9': ('AG', 'ANTIGUA AND BARBUDA'),
    'C1': ('AR', 'ARGENTINA'),
    '1B': ('AM', 'ARMENIA'),
    '1C': ('AW', 'ARUBA'),
    'C3': ('AU', 'AUSTRALIA'),
    'C4': ('AT', 'AUSTRIA'),
    '1D': ('AZ', 'AZERBAIJAN'),
    'C5': ('BS', 'BAHAMAS'),
    'C6': ('BH', 'BAHRAIN'),
    'C7': ('BD', 'BANGLADESH'),
    'C8': ('BB', 'BARBADOS'),
    '1F': ('BY', 'BELARUS'),
    'C9': ('BE', 'BELGIUM'),
    'D1': ('BZ', 'BELIZE'),
    'G6': ('BJ', 'BENIN'),
    'D0': ('BM', 'BERMUDA'),
    'D2': ('BT', 'BHUTAN'),
    'D3': ('BO', 'BOLIVIA'),
    '1E': ('BA', 'BOSNIA AND HERZEGOVINA'),
    'B1': ('BW', 'BOTSWANA'),
    'D4': ('BV', 'BOUVET ISLAND'),
    'D5': ('BR', 'BRAZIL'),
    'D6': ('IO', 'BRITISH INDIAN OCEAN TERRITORY'),
    'D9': ('BN', 'BRUNEI DARUSSALAM'),
    'E0': ('BG', 'BULGARIA'),
    'X2': ('BF', 'BURKINA FASO'),
    'E2': ('BI', 'BURUNDI'),
    'E3': ('KH', 'CAMBODIA'),
    'E4': ('CM', 'CAMEROON'),
    'E8': ('CV', 'CAPE VERDE'),
    'E9': ('KY', 'CAYMAN ISLANDS'),
    'F0': ('CF', 'CENTRAL AFRICAN REPUBLIC'),
    'F2': ('TD', 'CHAD'),
    'F3': ('CL', 'CHILE'),
    'F4': ('CN', 'CHINA'),
    'F6': ('CX', 'CHRISTMAS ISLAND'),
    'F7': ('CC', 'COCOS (KEELING) ISLANDS'),
    'F8': ('CO', 'COLOMBIA'),
    'F9': ('KM', 'COMOROS'),
    'G0': ('CG', 'CONGO'),
    'Y3': ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'),
    'G1': ('CK', 'COOK ISLANDS'),
    'G2': ('CR', 'COSTA RICA'),
    'L7': ('CI', "COTE D'IVOIRE"),
    '1M': ('HR', 'CROATIA'),
    'G3': ('CU', 'CUBA'),
    'G4': ('CY', 'CYPRUS'),
    '2N': ('CZ', 'CZECH REPUBLIC'),
    'G7': ('DK', 'DENMARK'),
    '1G': ('DJ', 'DJIBOUTI'),
    'G9': ('DM', 'DOMINICA'),
    'G8': ('DO', 'DOMINICAN REPUBLIC'),
    'H1': ('EC', 'ECUADOR'),
    'H2': ('EG', 'EGYPT'),
    'H3': ('SV', 'EL SALVADOR'),
    'H4': ('GQ', 'EQUATORIAL GUINEA'),
    '1J': ('ER', 'ERITREA'),
    '1H': ('EE', 'ESTONIA'),
    'H5': ('ET', 'ETHIOPIA'),
    'H7': ('FK', 'FALKLAND ISLANDS (MALVINAS)'),
    'H6': ('FO', 'FAROE ISLANDS'),
    'H8': ('FJ', 'FIJI'),
    'H9': ('FI', 'FINLAND'),
    'I0': ('FR', 'FRANCE'),
    'I3': ('GF', 'FRENCH GUIANA'),
    'I4': ('PF', 'FRENCH POLYNESIA'),
    '2C': ('TF', 'FRENCH SOUTHERN TERRITORIES'),
    'I5': ('GA', 'GABON'),
    'I6': ('GM', 'GAMBIA'),
    '2Q': ('GE', 'GEORGIA'),
    '2M': ('DE', 'GERMANY'),
    'J0': ('GH', 'GHANA'),
    'J1': ('GI', 'GIBRALTAR'),
    'J3': ('GR', 'GREECE'),
    'J4': ('GL', 'GREENLAND'),
    'J5': ('GD', 'GRENADA'),
    'J6': ('GP', 'GUADELOUPE'),
    'GU': ('GU', 'GUAM'),
    'J8': ('GT', 'GUATEMALA'),
    'Y7': ('GG', 'GUERNSEY'),
    'J9': ('GN', 'GUINEA'),
    'S0': ('GW', 'GUINEA-BISSAU'),
    'K0': ('GY', 'GUYANA'),
    'K1': ('HT', 'HAITI'),
    'K4': ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS'),
    'X4': ('VA', 'HOLY SEE (VATICAN CITY STATE)'),
    'K2': ('HN', 'HONDURAS'),
    'K3': ('HK', 'HONG KONG'),
    'K5': ('HU', 'HUNGARY'),
    'K6': ('IS', 'ICELAND'),
    'K7': ('IN', 'INDIA'),
    'K8': ('ID', 'INDONESIA'),
    'K9': ('IR', 'IRAN, ISLAMIC REPUBLIC OF'),
    'L0': ('IQ', 'IRAQ'),
    'L2': ('IE', 'IRELAND'),
    'Y8': ('IM', 'ISLE OF MAN'),
    'L3': ('IL', 'ISRAEL'),
    'L6': ('IT', 'ITALY'),
    'L8': ('JM', 'JAMAICA'),
    'M0': ('JP', 'JAPAN'),
    'Y9': ('JE', 'JERSEY'),
    'M2': ('JO', 'JORDAN'),
    '1P': ('KZ', 'KAZAKSTAN'),
    'M3': ('KE', 'KENYA'),
    'J2': ('KI', 'KIRIBATI'),
    'M4': ('KP', "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
    'M5': ('KR', 'KOREA, REPUBLIC OF'),
    'M6': ('KW', 'KUWAIT'),
    '1N': ('KG', 'KYRGYZSTAN'),
    'M7': ('LA', "LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
    '1R': ('LV', 'LATVIA'),
    'M8': ('LB', 'LEBANON'),
    'M9': ('LS', 'LESOTHO'),
    'N0': ('LR', 'LIBERIA'),
    'N1': ('LY', 'LIBYAN ARAB JAMAHIRIYA'),
    'N2': ('LI', 'LIECHTENSTEIN'),
    '1Q': ('LT', 'LITHUANIA'),
    'N4': ('LU', 'LUXEMBOURG'),
    'N5': ('MO', 'MACAU'),
    '1U': ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'),
    'N6': ('MG', 'MADAGASCAR'),
    'N7': ('MW', 'MALAWI'),
    'N8': ('MY', 'MALAYSIA'),
    'N9': ('MV', 'MALDIVES'),
    'O0': ('ML', 'MALI'),
    'O1': ('MT', 'MALTA'),
    '1T': ('MH', 'MARSHALL ISLANDS'),
    'O2': ('MQ', 'MARTINIQUE'),
    'O3': ('MR', 'MAURITANIA'),
    'O4': ('MU', 'MAURITIUS'),
    '2P': ('YT', 'MAYOTTE'),
    'O5': ('MX', 'MEXICO'),
    '1K': ('FM', 'MICRONESIA, FEDERATED STATES OF'),
    '1S': ('MD', 'MOLDOVA, REPUBLIC OF'),
    'O9': ('MC', 'MONACO'),
    'P0': ('MN', 'MONGOLIA'),
    'Z5': ('ME', 'MONTENEGRO'),
    'P1': ('MS', 'MONTSERRAT'),
    'P2': ('MA', 'MOROCCO'),
    'P3': ('MZ', 'MOZAMBIQUE'),
    'E1': ('MM', 'MYANMAR'),
    'T6': ('NA', 'NAMIBIA'),
    'P5': ('NR', 'NAURU'),
    'P6': ('NP', 'NEPAL'),
    'P7': ('NL', 'NETHERLANDS'),
    'P8': ('', 'NETHERLANDS ANTILLES'),
    '1W': ('NC', 'NEW CALEDONIA'),
    'Q2': ('NZ', 'NEW ZEALAND'),
    'Q3': ('NI', 'NICARAGUA'),
    'Q4': ('NE', 'NIGER'),
    'Q5': ('NG', 'NIGERIA'),
    'Q6': ('NU', 'NIUE'),
    'Q7': ('NF', 'NORFOLK ISLAND'),
    '1V': ('MP', 'NORTHERN MARIANA ISLANDS'),
    'Q8': ('NO', 'NORWAY'),
    'P4': ('OM', 'OMAN'),
    'R0': ('PK', 'PAKISTAN'),
    '1Y': ('PW', 'PALAU'),
    '1X': ('PS', 'PALESTINIAN TERRITORY, OCCUPIED'),
    'R1': ('PA', 'PANAMA'),
    'R2': ('PG', 'PAPUA NEW GUINEA'),
    'R4': ('PY', 'PARAGUAY'),
    'R5': ('PE', 'PERU'),
    'R6': ('PH', 'PHILIPPINES'),
    'R8': ('PN', 'PITCAIRN'),
    'R9': ('PL', 'POLAND'),
    'S1': ('PT', 'PORTUGAL'),
    'PR': ('PR', 'PUERTO RICO'),
    'S3': ('QA', 'QATAR'),
    'S4': ('RE', 'REUNION'),
    'S5': ('RO', 'ROMANIA'),
    '1Z': ('RU', 'RUSSIAN FEDERATION'),
    'S6': ('RW', 'RWANDA'),
    'Z0': ('BL', 'SAINT BARTHELEMY'),
    'U8': ('SH', 'SAINT HELENA'),
    'U7': ('KN', 'SAINT KITTS AND NEVIS'),
    'U9': ('LC', 'SAINT LUCIA'),
    'Z1': ('MF', 'SAINT MARTIN'),
    'V0': ('PM', 'SAINT PIERRE AND MIQUELON'),
    'V1': ('VC', 'SAINT VINCENT AND THE GRENADINES'),
    'Y0': ('WS', 'SAMOA'),
    'S8': ('SM', 'SAN MARINO'),
    'S9': ('ST', 'SAO TOME AND PRINCIPE'),
    'T0': ('SA', 'SAUDI ARABIA'),
    'T1': ('SN', 'SENEGAL'),
    'Z2': ('RS', 'SERBIA'),
    'T2': ('SC', 'SEYCHELLES'),
    'T8': ('SL', 'SIERRA LEONE'),
    'U0': ('SG', 'SINGAPORE'),
    '2B': ('SK', 'SLOVAKIA'),
    '2A': ('SI', 'SLOVENIA'),
    'D7': ('SB', 'SOLOMON ISLANDS'),
    'U1': ('SO', 'SOMALIA'),
    'T3': ('ZA', 'SOUTH AFRICA'),
    '1L': ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'),
    'U3': ('ES', 'SPAIN'),
    'F1': ('LK', 'SRI LANKA'),
    'V2': ('SD', 'SUDAN'),
    'V3': ('SR', 'SURINAME'),
    'L9': ('SJ', 'SVALBARD AND JAN MAYEN'),
    'V6': ('SZ', 'SWAZILAND'),
    'V7': ('SE', 'SWEDEN'),
    'V8': ('CH', 'SWITZERLAND'),
    'V9': ('SY', 'SYRIAN ARAB REPUBLIC'),
    'F5': ('TW', 'TAIWAN'),
    '2D': ('TJ', 'TAJIKISTAN'),
    'W0': ('TZ', 'TANZANIA, UNITED REPUBLIC OF'),
    'W1': ('TH', 'THAILAND'),
    'Z3': ('TL', 'TIMOR-LESTE'),
    'W2': ('TG', 'TOGO'),
    'W3': ('TK', 'TOKELAU'),
    'W4': ('TO', 'TONGA'),
    'W5': ('TT', 'TRINIDAD AND TOBAGO'),
    'W6': ('TN', 'TUNISIA'),
    'W8': ('TR', 'TURKEY'),
    '2E': ('TM', 'TURKMENISTAN'),
    'W7': ('TC', 'TURKS AND CAICOS ISLANDS'),
    '2G': ('TV', 'TUVALU'),
    'W9': ('UG', 'UGANDA'),
    '2H': ('UA', 'UKRAINE'),
    'C0': ('AE', 'UNITED ARAB EMIRATES'),
    'X0': ('GB', 'UNITED KINGDOM'),
    '2J': ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS'),
    'X3': ('UY', 'URUGUAY'),
    '2K': ('UZ', 'UZBEKISTAN'),
    '2L': ('VU', 'VANUATU'),
    'X5': ('VE', 'VENEZUELA'),
    'Q1': ('VN', 'VIET NAM'),
    'D8': ('VG', 'VIRGIN ISLANDS, BRITISH'),
    'VI': ('VI', 'VIRGIN ISLANDS, U.S.'),
    'X8': ('WF', 'WALLIS AND FUTUNA'),
    'U5': ('EH', 'WESTERN SAHARA'),
    'T7': ('YE', 'YEMEN'),
    'Y4': ('ZM', 'ZAMBIA'),
    'Y5': ('ZW', 'ZIMBABWE'),
    'XX': ('', 'UNKNOWN'),
}


def edgar_country(code: str) -> tuple[str, str]:
    """``(iso_alpha2, sec_name)`` for an EDGAR code; ``("", "")`` if unknown."""
    return EDGAR_CODES.get((code or "").strip().upper(), ("", ""))
