"""Offline tests for the Markdown report builder.

Mirrors ``test_reporting_html.py`` over the same fixture: every section the
HTML report renders must have a Markdown equivalent, minus the two deliberate
divergences (no QR code, relationship tables instead of SVG diagrams).
"""

from __future__ import annotations

from opencheck.reporting import build_report_markdown


def _report() -> dict:
    return {
        "lei": "2138000000000000A001",
        "legal_name": "Northwind Logistics Ltd",
        "jurisdiction": "GB",
        "derived_identifiers": {"company_number": "08123456"},
        "hits": [
            {"source_id": "companies_house", "is_stub": False, "name": "Northwind Logistics Ltd",
             "summary": "Active private company, incorporated 2016-04-06."},
            {"source_id": "gleif", "is_stub": False, "name": "Northwind Logistics Ltd",
             "summary": "LEI issued; no parent reported."},
            {"source_id": "kvk", "is_stub": True, "name": "stub", "summary": "stub"},
        ],
        "risk_signals": [],
        "license_notices": [],
        "bods": [
            {"statementId": "ent-1", "recordType": "entity",
             "recordDetails": {"name": "Northwind Logistics Ltd",
                               "identifiers": [{"scheme": "XI-LEI", "id": "2138000000000000A001"}]},
             "source": {"description": "UK Companies House"}},
            {"statementId": "per-1", "recordType": "person",
             "recordDetails": {"names": [{"fullName": "Jane Eleanor Smith"}]}},
            {"statementId": "rel-1", "recordType": "relationship",
             "recordDetails": {"interestedParty": "per-1", "subject": "ent-1",
                               "interests": [{"type": "shareholding",
                                              "details": "ownership of shares",
                                              "share": {"exclusiveMinimum": 75, "maximum": 100},
                                              "startDate": "2016-04-06"}]},
             "source": {"description": "UK Companies House"}},
        ],
    }


def test_markdown_has_all_sections():
    md = build_report_markdown(_report())
    assert md.startswith("# OpenCheck due-diligence report — Northwind Logistics Ltd")
    assert "Identity confirmed by LEI" in md
    assert "## Identifiers" in md and "`2138000000000000A001`" in md
    assert "Company registration number" in md and "`08123456`" in md
    assert "## Run a live check" in md
    assert "https://opencheck.world/?lei=2138000000000000A001" in md
    assert "## Risk signals" in md
    assert "## What each source found" in md
    assert "## Ownership & control structure" in md
    assert "## Licensing & attribution" in md
    # The two deliberate divergences from the PDF pipeline.
    assert "<svg" not in md
    assert "qr" not in md.lower()


def test_relationship_table_replaces_diagram():
    md = build_report_markdown(_report())
    # Same rows the PDF's text-equivalent table gets, as a pipe table.
    assert "| Interested party | Interest | Subject |" in md
    assert "Jane Eleanor Smith" in md
    assert "Northwind Logistics Ltd" in md
    assert "### UK Companies House" in md


def test_summary_included_only_when_narrative_present():
    md_without = build_report_markdown(_report())
    assert "## Summary" not in md_without
    narrative = {
        "summary": "Northwind Logistics Ltd is an identity-confirmed entity.",
        "overall_confidence": "high",
        "model": "claude-sonnet-4-6",
        "prompt_version": "2026-06-14-v3",
        "packet": {"facts": [{"source_name": "UK Companies House"}]},
    }
    md_with = build_report_markdown(_report(), narrative=narrative)
    assert "## Summary (high confidence)" in md_with
    assert "identity-confirmed entity" in md_with
    assert "**Evidence:** UK Companies House" in md_with
    assert "Generated by claude-sonnet-4-6" in md_with


def test_claims_and_dispositions_render():
    narrative = {
        "summary": "Summary text.",
        "overall_confidence": "medium",
        "packet": {"facts": [{"id": "f1", "source_name": "GLEIF"}],
                   "gaps": [{"id": "g1", "statement": "No sanctions screening for related parties."}]},
        "claims": [
            {"id": "c1", "text": "The entity is active.", "fact_ids": ["f1"]},
            {"id": "c2", "text": "The LEI is current.", "fact_ids": []},
        ],
    }
    dispositions = {
        "dispositions": [
            {"claim_id": "c1", "status": "accepted", "decided_at": "2026-07-20T09:00:00Z",
             "comment": "Verified against the register."},
        ],
    }
    md = build_report_markdown(_report(), narrative=narrative, dispositions=dispositions)
    assert "### Claims and analyst dispositions" in md
    assert "**Analyst review:** 1 accepted · 1 undecided" in md
    assert "The entity is active. — *GLEIF* **[Accepted · 2026-07-20]**" in md
    assert "Analyst note: Verified against the register." in md
    # Gaps are always rendered from the packet, never from the model's prose.
    assert "### Not verified in this check" in md
    assert "No sanctions screening for related parties." in md


def test_no_risk_signals_states_checks_applied():
    md = build_report_markdown(_report())
    assert "**No risk signals were raised**" in md


def test_risk_signals_render_with_confidence():
    report = _report()
    report["risk_signals"] = [
        {"code": "NON_EU_JURISDICTION", "confidence": "high",
         "summary": "Registered outside the EU/EEA.", "source_id": ""},
    ]
    md = build_report_markdown(report)
    assert "- **Non Eu Jurisdiction** (high) — Registered outside the EU/EEA." in md


def test_pipe_characters_escaped_in_table_cells():
    report = _report()
    report["hits"][0]["summary"] = "Active | private company."
    report["bods"][2]["recordDetails"]["interests"][0]["details"] = "shares | class A"
    md = build_report_markdown(report)
    # A raw " | " inside a cell would silently add a table column.
    assert "shares \\| class A" in md


def test_stub_only_report_omits_sources_section():
    report = _report()
    report["hits"] = [h for h in report["hits"] if h["is_stub"]]
    md = build_report_markdown(report)
    assert "## What each source found" not in md
