/**
 * NarrativePanel — an on-demand, source-cited narrative summary of the current
 * entity, generated by the backend /narrative endpoint.
 *
 * Trust model (mirrors the backend): the panel never shows a claim that isn't
 * grounded. Each claim carries the evidence ids (facts / risks / gaps) it cites;
 * clicking a citation chip scrolls to the originating source card and asks the
 * BODS graph to highlight the cited statement (via an `oc:cite` window event).
 *
 * The summary is generated only when the user clicks "Generate summary" so we
 * don't spend a model call on every lookup.
 */

import { useEffect, useState } from "react";
import {
  downloadReportPdf,
  fetchCuratedNarrative,
  fetchNarrative,
  type EvidencePacket,
  type NarrativeResponse,
} from "../../lib/api";
import { CONFIDENCE_DOT } from "../risk/RiskChip";

const CONF_BADGE: Record<string, string> = {
  high: "bg-emerald-50 text-emerald-700 border-emerald-200",
  medium: "bg-amber-50 text-amber-800 border-amber-200",
  low: "bg-slate-100 text-slate-600 border-slate-300",
};

interface Cite {
  id: string;
  kind: "fact" | "risk" | "gap";
  label: string;
  sourceId: string | null;
  statementId: string | null;
  confidence: string | null;
}

/** Resolve an evidence id (f/r/g) to a displayable, clickable citation. */
function resolveCite(packet: EvidencePacket, id: string): Cite | null {
  const fact = packet.facts.find((f) => f.id === id);
  if (fact) {
    return {
      id,
      kind: "fact",
      label: fact.source_name,
      sourceId: fact.source_id,
      statementId: fact.bods_statement_ids[0] ?? null,
      confidence: fact.confidence,
    };
  }
  const risk = packet.risks.find((r) => r.id === id);
  if (risk) {
    return {
      id,
      kind: "risk",
      label: risk.source_name,
      sourceId: risk.source_id,
      statementId: null,
      confidence: risk.confidence,
    };
  }
  const gap = packet.gaps.find((g) => g.id === id);
  if (gap) {
    return { id, kind: "gap", label: "Limitation", sourceId: null, statementId: null, confidence: null };
  }
  return null;
}

/** Scroll to the cited source card, flash it, and ask graphs to highlight. */
function focusCitation(cite: Cite) {
  if (cite.sourceId) {
    const el = document.getElementById(`oc-source-${cite.sourceId}`);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
      el.classList.add("oc-cite-flash");
      window.setTimeout(() => el.classList.remove("oc-cite-flash"), 1600);
    }
  }
  window.dispatchEvent(
    new CustomEvent("oc:cite", {
      detail: { sourceId: cite.sourceId, statementId: cite.statementId },
    }),
  );
}

function CitationChip({ cite }: { cite: Cite }) {
  const tone =
    cite.kind === "gap"
      ? "bg-slate-50 text-slate-600 border-slate-300"
      : "bg-[#eef1fb] text-oo-blue border-[#cfd6f5] hover:bg-[#e3e8f8]";
  return (
    <button
      type="button"
      onClick={() => focusCitation(cite)}
      title={cite.statementId ? "Show source and highlight in the ownership graph" : "Show source"}
      className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-medium transition-colors ${tone}`}
    >
      {cite.confidence && (
        <span aria-hidden className="text-[9px]">{CONFIDENCE_DOT[cite.confidence] ?? "•"}</span>
      )}
      <span>{cite.label}</span>
    </button>
  );
}

export function NarrativePanel({ lei }: { lei: string; legalName?: string | null }) {
  const [data, setData] = useState<NarrativeResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [pdfBusy, setPdfBusy] = useState(false);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState(false);
  const [cached, setCached] = useState(false);

  // Curated examples ship a pre-baked, cited summary so first-time visitors see
  // the feature instantly with no model call. Reset + try the cache on every
  // entity change; live lookups have no cached file and fall back to the button.
  useEffect(() => {
    let active = true;
    setData(null);
    setError(null);
    setCached(false);
    fetchCuratedNarrative(lei).then((cachedNarrative) => {
      if (active && cachedNarrative) {
        setData(cachedNarrative);
        setCached(true);
      }
    });
    return () => {
      active = false;
    };
  }, [lei]);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      setData(await fetchNarrative(lei));
      setCached(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not generate the summary.");
    } finally {
      setLoading(false);
    }
  }

  async function downloadPdf() {
    setPdfBusy(true);
    setPdfError(null);
    try {
      // Embed the summary in the PDF only if it has been generated here.
      await downloadReportPdf(lei, data);
    } catch (e) {
      setPdfError(e instanceof Error ? e.message : "Could not generate the PDF.");
    } finally {
      setPdfBusy(false);
    }
  }

  return (
    <section className="mb-8 bg-white border border-oo-rule rounded-oo p-5 lg:p-7 transition-shadow hover:shadow-oo-card">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <h2 className="text-[15px] font-semibold text-oo-navy flex items-center gap-2">
            AI summary
            <span className="text-[10px] font-medium uppercase tracking-wide text-oo-blue border border-[#cfd6f5] bg-[#eef1fb] rounded-full px-1.5 py-0.5">
              Beta
            </span>
          </h2>
          <p className="text-[12px] text-oo-muted mt-0.5">
            A plain-English summary of what OpenCheck found — every statement links to its source.
          </p>
        </div>
        {/* Pinned in the top-right corner at every width — never overflows the card. */}
        <button
          type="button"
          onClick={downloadPdf}
          disabled={pdfBusy}
          title="Download an accessible PDF report of these findings"
          className="shrink-0 whitespace-nowrap inline-flex items-center gap-1.5 rounded-oo border border-oo-blue text-oo-blue text-[12px] font-medium px-3 py-1.5 hover:bg-[#eef1fb] disabled:opacity-60"
        >
          {pdfBusy ? "Preparing PDF…" : "Download PDF"}
        </button>
      </div>

      {data && (
        <div className="mt-3 flex items-center flex-wrap gap-2">
          <span
            className={`text-[11px] font-medium border rounded-full px-2 py-0.5 ${
              CONF_BADGE[data.overall_confidence] ?? CONF_BADGE.low
            }`}
          >
            {data.overall_confidence} confidence
          </span>
          <button
            type="button"
            onClick={() => setCollapsed((c) => !c)}
            aria-expanded={!collapsed}
            title={collapsed ? "Show summary" : "Hide summary"}
            className="inline-flex items-center gap-1 rounded-oo border border-oo-rule text-oo-muted text-[12px] font-medium px-3 py-1.5 hover:border-oo-blue hover:text-oo-blue transition-colors"
          >
            {collapsed ? (
              <>
                Show
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-3.5 h-3.5">
                  <path fillRule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clipRule="evenodd"/>
                </svg>
              </>
            ) : (
              <>
                Hide
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-3.5 h-3.5">
                  <path fillRule="evenodd" d="M11.78 9.78a.75.75 0 0 1-1.06 0L8 7.06 5.28 9.78a.75.75 0 0 1-1.06-1.06l3.25-3.25a.75.75 0 0 1 1.06 0l3.25 3.25a.75.75 0 0 1 0 1.06Z" clipRule="evenodd"/>
                </svg>
              </>
            )}
          </button>
        </div>
      )}
      {pdfError && (
        <p className="mt-2 text-[12px] text-amber-800 bg-amber-50 border border-amber-200 rounded-oo px-3 py-2">
          {pdfError}
        </p>
      )}

      {!data && !collapsed && (
        <div className="mt-4">
          <button
            type="button"
            onClick={generate}
            disabled={loading}
            className="inline-flex items-center gap-2 rounded-oo bg-oo-blue text-white text-[13px] font-medium px-4 py-2 disabled:opacity-60"
          >
            {loading ? "Generating…" : "Generate summary"}
          </button>
          {error && (
            <p className="mt-3 text-[12px] text-amber-800 bg-amber-50 border border-amber-200 rounded-oo px-3 py-2">
              {error}
            </p>
          )}
        </div>
      )}

      {data && !collapsed && (
        <div className="mt-4">
          <p className="text-[14px] leading-relaxed text-oo-ink">{data.summary}</p>

          {data.claims.length > 0 && (
            <div className="mt-4 border-t border-oo-rule pt-3">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-oo-muted mb-2">
                Evidence
              </p>
              <ul className="space-y-2">
                {data.claims.map((c) => {
                  const cites = c.fact_ids
                    .map((id) => resolveCite(data.packet, id))
                    .filter((x): x is Cite => x !== null);
                  return (
                    <li key={c.id} className="text-[13px] text-oo-ink">
                      <span>{c.text}</span>{" "}
                      <span className="inline-flex flex-wrap gap-1 align-middle">
                        {cites.map((cite) => (
                          <CitationChip key={`${c.id}-${cite.id}`} cite={cite} />
                        ))}
                      </span>
                    </li>
                  );
                })}
              </ul>
            </div>
          )}

          {data.limitations.length > 0 && (
            <div className="mt-4">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-oo-muted mb-1">
                Limitations
              </p>
              <ul className="list-disc pl-5 space-y-0.5">
                {data.limitations.map((l, i) => (
                  <li key={i} className="text-[12px] text-oo-muted">{l}</li>
                ))}
              </ul>
            </div>
          )}

          {!data.validation_ok && (
            <p className="mt-3 text-[12px] text-amber-800 bg-amber-50 border border-amber-200 rounded-oo px-3 py-2">
              {data.dropped_claims.length} statement
              {data.dropped_claims.length === 1 ? " was" : "s were"} withheld because they could not be
              tied to a source.
            </p>
          )}

          <p className="mt-4 text-[11px] text-oo-muted border-t border-oo-rule pt-3">
            {cached && (
              <span className="font-medium text-oo-ink">Saved example summary. </span>
            )}
            AI-generated from OpenCheck&rsquo;s data. Every claim is grounded in the cited sources; nothing
            is added beyond what they state. Generated by {data.model} · prompt {data.prompt_version}.{" "}
            <button type="button" onClick={generate} className="text-oo-blue hover:underline">
              {cached ? "Regenerate live" : "Regenerate"}
            </button>
          </p>
        </div>
      )}
    </section>
  );
}
