/**
 * NarrativePanel — an on-demand, source-cited narrative summary of the current
 * entity, generated by the backend /narrative endpoint.
 *
 * Trust model (mirrors the backend): the panel never shows a claim that isn't
 * grounded. Each claim carries the evidence ids (facts / risks / gaps) it cites;
 * clicking a citation chip scrolls to the originating source card and asks the
 * BODS graph to highlight the cited statement (via an `oc:cite` window event).
 *
 * The summary is generated only when the user clicks "Generate summary" so we
 * don't spend a model call on every lookup.
 *
 * Analyst control plane: each claim can be marked Accepted / Disputed / Needs
 * review with an optional note. Dispositions are persisted server-side keyed to
 * the narrative's `run_id` (a regenerate starts a fresh sheet) and are embedded
 * in the PDF export, turning the report into the analyst's defensible record.
 * Curated (pre-baked) example summaries have no live run to bind to, so their
 * controls are hidden until the user regenerates live.
 */

import { useEffect, useRef, useState } from "react";
import { trackEvent } from "../../lib/analytics";
import {
  fetchCuratedNarrative,
  fetchNarrative,
  getDispositions,
  putDispositions,
  type DispositionRecord,
  type DispositionStatus,
  type EvidencePacket,
  type NarrativeResponse,
} from "../../lib/api";
import {
  EVIDENCE_PREVIEW_COUNT,
  citedSourceLabels,
  shouldCollapseEvidence,
} from "../../lib/evidenceDisclosure";
import { CONFIDENCE_GLYPH, CONFIDENCE_LABEL } from "../ui/Chip";
import { Chip, SectionHeading } from "../ui";

const CONF_BADGE: Record<string, string> = {
  high: "bg-emerald-50 text-emerald-700 border-emerald-200",
  medium: "bg-amber-50 text-amber-800 border-amber-200",
  low: "bg-slate-100 text-slate-600 border-slate-300",
};

interface Cite {
  id: string;
  kind: "fact" | "risk" | "gap";
  label: string;
  sourceId: string | null;
  statementId: string | null;
  confidence: string | null;
}

/** Resolve an evidence id (f/r/g) to a displayable, clickable citation. */
function resolveCite(packet: EvidencePacket, id: string): Cite | null {
  const fact = packet.facts.find((f) => f.id === id);
  if (fact) {
    return {
      id,
      kind: "fact",
      label: fact.source_name,
      sourceId: fact.source_id,
      statementId: fact.bods_statement_ids[0] ?? null,
      confidence: fact.confidence,
    };
  }
  const risk = packet.risks.find((r) => r.id === id);
  if (risk) {
    return {
      id,
      kind: "risk",
      label: risk.source_name,
      sourceId: risk.source_id,
      statementId: null,
      confidence: risk.confidence,
    };
  }
  const gap = packet.gaps.find((g) => g.id === id);
  if (gap) {
    return { id, kind: "gap", label: "Limitation", sourceId: null, statementId: null, confidence: null };
  }
  return null;
}

/** Scroll to the cited source card, flash it, and ask graphs to highlight. */
function focusCitation(cite: Cite) {
  if (cite.sourceId) {
    const el = document.getElementById(`oc-source-${cite.sourceId}`);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
      if (el.tabIndex < 0) el.tabIndex = -1;
      el.focus({ preventScroll: true });
      el.classList.add("oc-cite-flash");
      window.setTimeout(() => el.classList.remove("oc-cite-flash"), 1600);
    }
  }
  window.dispatchEvent(
    new CustomEvent("oc:cite", {
      detail: { sourceId: cite.sourceId, statementId: cite.statementId },
    }),
  );
}

function CitationChip({ cite }: { cite: Cite }) {
  const tone =
    cite.kind === "gap"
      ? "bg-slate-50 text-slate-600 border-slate-300"
      : "bg-[#eef1fb] text-oo-blue border-[#cfd6f5] hover:bg-[#e3e8f8]";
  return (
    <button
      type="button"
      onClick={() => focusCitation(cite)}
      className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-oo-meta font-medium transition-colors ${tone}`}
    >
      {cite.confidence && (
        <>
          <span aria-hidden className="text-oo-meta">{CONFIDENCE_GLYPH[cite.confidence] ?? "•"}</span>
          {/* v1 announced the bare level ("high confidence"). What the level
              means is the useful part, and it already exists as prose. */}
          <span className="sr-only">{CONFIDENCE_LABEL[cite.confidence] ?? cite.confidence}: </span>
        </>
      )}
      <span>{cite.label}</span>
      {/* What activating the chip does — until Phase 124 this was a `title`,
          and the graph-highlight behaviour was described nowhere else. */}
      <span className="sr-only">
        {cite.statementId
          ? " — shows the source and highlights it in the ownership diagram"
          : " — shows the source"}
      </span>
    </button>
  );
}

// ---------------------------------------------------------------------------
// Analyst dispositions
// ---------------------------------------------------------------------------

interface DispState {
  status: DispositionStatus;
  comment: string;
}

const DISP_OPTIONS: { status: DispositionStatus; label: string; active: string }[] = [
  { status: "accepted", label: "Accept", active: "bg-emerald-50 text-emerald-700 border-emerald-300" },
  { status: "disputed", label: "Dispute", active: "bg-rose-50 text-rose-700 border-rose-300" },
  { status: "needs_review", label: "Needs review", active: "bg-slate-100 text-slate-700 border-slate-400" },
];

function DispositionControls({
  claimId,
  value,
  commentOpen,
  onStatus,
  onComment,
  onToggleComment,
}: {
  claimId: string;
  value: DispState | undefined;
  commentOpen: boolean;
  onStatus: (s: DispositionStatus) => void;
  onComment: (text: string) => void;
  onToggleComment: () => void;
}) {
  const commentId = `oc-disp-comment-${claimId}`;
  const hasComment = Boolean(value?.comment);
  return (
    <span className="mt-1 flex flex-wrap items-center gap-1">
      <span
        role="group"
        aria-label="Analyst disposition for this claim"
        className="inline-flex items-center gap-1"
      >
        {DISP_OPTIONS.map((opt) => {
          const selected = value?.status === opt.status;
          return (
            <button
              key={opt.status}
              type="button"
              aria-pressed={selected}
              onClick={() => onStatus(opt.status)}
              className={`rounded-full border px-2 py-0.5 text-[11px] font-medium transition-colors ${
                selected
                  ? opt.active
                  : "bg-white text-oo-muted border-oo-rule hover:border-oo-blue hover:text-oo-blue"
              }`}
            >
              {opt.label}
              {selected && <span className="sr-only"> (selected)</span>}
            </button>
          );
        })}
      </span>
      <button
        type="button"
        aria-expanded={commentOpen}
        aria-controls={commentId}
        onClick={onToggleComment}
        className="rounded-full border border-oo-rule bg-white px-2 py-0.5 text-[11px] font-medium text-oo-muted hover:border-oo-blue hover:text-oo-blue transition-colors"
      >
        {hasComment ? "Edit note" : "Add note"}
      </button>
      {commentOpen && (
        <span className="basis-full">
          <label htmlFor={commentId} className="sr-only">
            Analyst note for this statement
          </label>
          <textarea
            id={commentId}
            value={value?.comment ?? ""}
            onChange={(e) => onComment(e.target.value)}
            maxLength={2000}
            rows={2}
            placeholder="Why is this accepted, disputed or held for review?"
            className="mt-1 w-full rounded-oo border border-oo-rule p-2 text-[12px] text-oo-ink placeholder:text-[#6b7280] focus:border-oo-blue focus:outline-none focus:ring-1 focus:ring-oo-blue/30"
          />
        </span>
      )}
    </span>
  );
}

/** What the report's PDF and Markdown exports embed: the summary as generated
 *  on this page, and the analyst's decisions about it. Both are nullable — the
 *  reports are downloadable before a summary has been generated. */
export interface ReportExportPayload {
  narrative: NarrativeResponse | null;
  dispositions: DispositionRecord | null;
}

export function NarrativePanel({
  lei,
  onExportPayload,
}: {
  lei: string;
  /** Hand the report's export payload (narrative + analyst dispositions) up to
   *  whoever owns the "Share and export" control. */
  onExportPayload?: (payload: ReportExportPayload) => void;
}) {
  const [data, setData] = useState<NarrativeResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState(false);
  const [cached, setCached] = useState(false);
  // Evidence disclosure: long claim lists start collapsed to a preview (see
  // lib/evidenceDisclosure.ts for the rules). This flag records only that the
  // user explicitly expanded — whether the section is collapsible at all is
  // derived per render, so sign-off becoming active auto-expands it.
  const [evidenceExpanded, setEvidenceExpanded] = useState(false);

  // Analyst dispositions, keyed by claim id. Persisted (debounced) against the
  // narrative's run_id; hydrated from the server when a stored sheet exists.
  const [disp, setDisp] = useState<Record<string, DispState>>({});
  const [commentOpen, setCommentOpen] = useState<Record<string, boolean>>({});
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  // "I have read this summary" — a weaker statement than accepting every
  // claim in it, so it is stored and rendered separately from the per-claim
  // dispositions and never derived from them.
  const [reviewed, setReviewed] = useState(false);
  const dirtyRef = useRef(false);
  // The stored sheet has been fetched (or confirmed absent). No save may run
  // before it is true: a whole-sheet overwrite racing its own hydration is how
  // one click deleted an analyst's saved decisions.
  const hydratedRef = useRef(false);
  // An edit is waiting on the debounce.
  const pendingRef = useRef(false);
  const saveTimerRef = useRef<number | null>(null);

  const canSignOff = Boolean(data?.run_id) && !cached;

  // Curated examples ship a pre-baked, cited summary so first-time visitors see
  // the feature instantly with no model call. Reset + try the cache on every
  // entity change; live lookups have no cached file and fall back to the button.
  useEffect(() => {
    let active = true;
    setData(null);
    setError(null);
    setCached(false);
    setDisp({});
    setCommentOpen({});
    setSaveState("idle");
    setEvidenceExpanded(false);
    setReviewed(false);
    dirtyRef.current = false;
    pendingRef.current = false;
    hydratedRef.current = false;
    fetchCuratedNarrative(lei).then((cachedNarrative) => {
      if (active && cachedNarrative) {
        setData(cachedNarrative);
        setCached(true);
      }
    });
    return () => {
      active = false;
    };
  }, [lei]);

  // Hydrate any stored disposition sheet for this exact narrative run.
  //
  // The first version bailed entirely when the analyst had already touched
  // something (`dirtyRef`), which lost the stored sheet: the save is a
  // whole-sheet overwrite, so one click on "Mark as reviewed" landing before
  // this promise resolved wrote back an empty `dispositions: []` and deleted
  // every decision and `decided_at` on the server. Stored entries are now
  // merged *under* local ones — the analyst's own edits win, everything they
  // have not touched survives.
  useEffect(() => {
    if (!data?.run_id || cached) return;
    let active = true;
    getDispositions(lei, data.run_id).then((record) => {
      if (!active) return;
      if (record) {
        const stored: Record<string, DispState> = {};
        for (const d of record.dispositions) {
          stored[d.claim_id] = { status: d.status, comment: d.comment ?? "" };
        }
        setDisp((local) => ({ ...stored, ...local }));
        if (!dirtyRef.current) setReviewed(Boolean(record.reviewed));
      }
      // Set last, and on both branches: until it is true no save may run, or
      // the save would race the very sheet it is about to overwrite.
      hydratedRef.current = true;
    });
    return () => {
      active = false;
    };
  }, [lei, data?.run_id, cached]);

  // Debounced persistence: any analyst change is written ~800 ms after the
  // last edit (whole-sheet overwrite; timestamps are stamped server-side).
  useEffect(() => {
    if (!dirtyRef.current || !data?.run_id || cached) return;
    const runId = data.run_id;
    const promptVersion = data.prompt_version;
    const model = data.model;
    if (!hydratedRef.current) return;
    const save = async () => {
      setSaveState("saving");
      try {
        await putDispositions(
          lei,
          runId,
          Object.entries(disp).map(([claimId, d]) => ({
            claim_id: claimId,
            status: d.status,
            comment: d.comment.trim() ? d.comment.trim() : null,
          })),
          { prompt_version: promptVersion, model, reviewed },
        );
        setSaveState("saved");
      } catch {
        setSaveState("error");
      }
    };
    if (saveTimerRef.current !== null) window.clearTimeout(saveTimerRef.current);
    saveTimerRef.current = window.setTimeout(save, 800);
    return () => {
      if (saveTimerRef.current === null) return;
      window.clearTimeout(saveTimerRef.current);
      saveTimerRef.current = null;
      // Flush rather than drop. This panel is mounted only under
      // `mode === "quick"`, so switching to FullCheck within the debounce
      // window unmounted it and silently discarded the pending write — the
      // control had already drawn a checkmark for a review that was never
      // persisted. `void` because a cleanup cannot await, and the request is
      // an idempotent whole-sheet overwrite, so a duplicate is harmless.
      if (pendingRef.current) void save();
    };
  }, [disp, reviewed, data, cached, lei]);

  // Set on every analyst edit and cleared once a save completes, so the
  // unmount flush above can tell "nothing to write" from "a write is due".
  useEffect(() => {
    if (saveState === "saved") pendingRef.current = false;
  }, [saveState]);

  function toggleReviewed() {
    dirtyRef.current = true;
    pendingRef.current = true;
    setReviewed((v) => !v);
  }

  function setClaimStatus(claimId: string, status: DispositionStatus) {
    dirtyRef.current = true;
    pendingRef.current = true;
    setDisp((prev) => {
      const current = prev[claimId];
      // Clicking the active status again clears the decision.
      if (current?.status === status && !current.comment) {
        const next = { ...prev };
        delete next[claimId];
        return next;
      }
      return { ...prev, [claimId]: { status, comment: current?.comment ?? "" } };
    });
  }

  function setClaimComment(claimId: string, comment: string) {
    dirtyRef.current = true;
    pendingRef.current = true;
    setDisp((prev) => {
      const current = prev[claimId];
      return {
        ...prev,
        [claimId]: { status: current?.status ?? "needs_review", comment },
      };
    });
  }

  /** The audit trail embedded in the PDF and the Markdown report. */
  function buildRecord(): DispositionRecord | null {
    if (!data?.run_id || cached) return null;
    const entries = Object.entries(disp);
    // A summary marked reviewed with no claim dispositioned is still a
    // decision, and the exported report is where a decision has to appear —
    // the first version returned null here, so the one analyst who read the
    // summary and signed it off exported a report with no audit trail at all.
    if (entries.length === 0 && !reviewed) return null;
    return {
      lei,
      run_id: data.run_id,
      prompt_version: data.prompt_version,
      model: data.model,
      reviewer: null,
      reviewed,
      dispositions: entries.map(([claimId, d]) => ({
        claim_id: claimId,
        status: d.status,
        comment: d.comment.trim() ? d.comment.trim() : null,
      })),
    };
  }

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      setData(await fetchNarrative(lei));
      setCached(false);
      setDisp({});
      setCommentOpen({});
      setSaveState("idle");
      setEvidenceExpanded(false);
      // A regenerate is new text and therefore a new run_id, which is the
      // whole reason run_id exists (see `compute_run_id`): decisions must
      // never attach to words the analyst did not read. `reviewed` is one of
      // those decisions — leaving it set carried a checkmark, and then a
      // stamped `reviewed_at`, onto a summary produced two seconds ago.
      setReviewed(false);
      dirtyRef.current = false;
      pendingRef.current = false;
      // The new run has no stored sheet yet; the hydrate effect will confirm.
      hydratedRef.current = false;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not generate the summary.");
    } finally {
      setLoading(false);
    }
  }

  // Publish what the report exports should embed. The PDF and Markdown routes
  // post this card's narrative and dispositions, which is why the export
  // control used to live in this card's header — halfway down the page, under
  // a heading about something else. The control moved to the subject; the data
  // it needs comes up from here instead.
  const record = buildRecord();
  useEffect(() => {
    onExportPayload?.({ narrative: data, dispositions: record });
    // `record` is rebuilt every render, so depend on what it is derived from.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, disp, reviewed, cached, onExportPayload]);

  const decidedCount = data ? data.claims.filter((c) => disp[c.id]).length : 0;
  // Long evidence lists start collapsed to a preview — except while sign-off
  // is active, when the disposition controls must all stay reachable.
  const evidenceCollapsible = data
    ? shouldCollapseEvidence(data.claims.length, canSignOff)
    : false;
  const evidenceCollapsed = evidenceCollapsible && !evidenceExpanded;
  const citedSources = data ? citedSourceLabels(data.claims, data.packet) : [];
  const tally = {
    accepted: Object.values(disp).filter((d) => d.status === "accepted").length,
    disputed: Object.values(disp).filter((d) => d.status === "disputed").length,
    needs_review: Object.values(disp).filter((d) => d.status === "needs_review").length,
  };

  return (
    <section className="px-4 py-[18px] sm:px-6 sm:py-[22px] border-b border-oo-rule">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          {/* "Summary", not "AI summary" + a Beta badge.

              The v1 heading named the machinery and graded it, which is two
              statements about OpenCheck where the reader wanted one about the
              company. What actually needs saying is the provenance — that a
              model wrote it and every sentence carries a citation — so that
              is what the chip beside the heading says, in words rather than
              in a status label a reader has to interpret. */}
          <div className="flex items-center flex-wrap gap-2">
            <SectionHeading>Summary</SectionHeading>
            <Chip tone="accent" size="sm">
              Written by AI, cited to sources
            </Chip>
          </div>
        </div>
      </div>

      {data && (
        <div className="mt-3 flex items-center flex-wrap gap-2">
          <span
            className={`text-[11px] font-medium border rounded-full px-2 py-0.5 ${
              CONF_BADGE[data.overall_confidence] ?? CONF_BADGE.low
            }`}
          >
            {data.overall_confidence} confidence
          </span>
          <button
            type="button"
            onClick={() => setCollapsed((c) => !c)}
            aria-expanded={!collapsed}
            className="inline-flex items-center gap-1 rounded-oo border border-oo-rule text-oo-muted text-[12px] font-medium px-3 py-1.5 hover:border-oo-blue hover:text-oo-blue transition-colors"
          >
            {collapsed ? (
              <>
                Show
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-3.5 h-3.5">
                  <path fillRule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clipRule="evenodd"/>
                </svg>
              </>
            ) : (
              <>
                Hide
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-3.5 h-3.5">
                  <path fillRule="evenodd" d="M11.78 9.78a.75.75 0 0 1-1.06 0L8 7.06 5.28 9.78a.75.75 0 0 1-1.06-1.06l3.25-3.25a.75.75 0 0 1 1.06 0l3.25 3.25a.75.75 0 0 1 0 1.06Z" clipRule="evenodd"/>
                </svg>
              </>
            )}
          </button>
        </div>
      )}

      {!data && !collapsed && (
        <div className="mt-4">
          <button
            type="button"
            onClick={generate}
            disabled={loading}
            className="inline-flex items-center gap-2 rounded-oo bg-oo-blue text-white text-[13px] font-medium px-4 py-2 disabled:opacity-60"
          >
            {loading ? "Generating…" : "Generate summary"}
          </button>
          {error && (
            <p role="alert" className="mt-3 text-[12px] text-amber-800 bg-amber-50 border border-amber-200 rounded-oo px-3 py-2">
              {error}
            </p>
          )}
        </div>
      )}

      {data && !collapsed && (
        <div className="mt-4">
          <p className="text-[14px] leading-relaxed text-oo-ink max-w-[82ch]">{data.summary}</p>

          {/* The control that acts on the summary as a whole, above the
              evidence list rather than after it, because a reader who has
              finished the prose is at this point on the page.

              It used to carry "Every sentence links to the record it came
              from." — copied from the mockup, where the citations are chips
              inline in the prose. Ours are not: they are a separate evidence
              list below, and the sentences themselves link to nothing. The
              claim was false as rendered, which is the one thing this report
              is not allowed to be. It comes back if and when the citations
              move inline. */}
          <div className="mt-3.5 flex items-center flex-wrap gap-x-4 gap-y-2 text-oo-small">
            {canSignOff && (
              <button
                type="button"
                onClick={toggleReviewed}
                aria-pressed={reviewed}
                className={`inline-flex items-center gap-1.5 font-medium ${
                  reviewed ? "text-oo-ok-text" : "text-oo-blue hover:underline"
                }`}
              >
                {reviewed ? (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
                      stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"
                      strokeLinejoin="round" aria-hidden="true">
                      <path d="m20 6-11 11-5-5" />
                    </svg>
                    Reviewed
                  </>
                ) : (
                  "Mark as reviewed"
                )}
              </button>
            )}
            {/* Beside the control, not four hundred pixels below it in a block
                that only renders when the narrative has claims. The button
                draws its checkmark optimistically, so a failed write was
                reported nowhere on a claimless summary and silently reverted
                on reload. */}
            {canSignOff && saveState !== "idle" && (
              <span
                role="status"
                className={saveState === "error" ? "text-oo-warn-text" : "text-oo-muted"}
              >
                {saveState === "saving"
                  ? "Saving…"
                  : saveState === "saved"
                    ? "Saved"
                    : "Could not save — your decisions are not stored."}
              </span>
            )}
          </div>

          {data.claims.length > 0 && (
            <div className="mt-4 border-t border-oo-rule pt-3">
              <div className="flex items-baseline justify-between flex-wrap gap-2 mb-2">
                <p className="text-[11px] font-semibold uppercase tracking-wide text-oo-muted">
                  Evidence
                  {/* The full count stays visible even while collapsed, so the
                      card's grounding promise is asserted at a glance. */}
                  <span className="normal-case tracking-normal font-normal">
                    {" "}· {data.claims.length} claim{data.claims.length === 1 ? "" : "s"}
                    {citedSources.length > 0 && (
                      <>
                        , cited to {citedSources.length} source
                        {citedSources.length === 1 ? "" : "s"}
                      </>
                    )}
                  </span>
                </p>
                {canSignOff && (
                  <p role="status" className="text-[11px] text-oo-muted">
                    {decidedCount === 0
                      ? "Review each claim: accept, dispute, or hold for review."
                      : [
                          tally.accepted ? `${tally.accepted} accepted` : null,
                          tally.disputed ? `${tally.disputed} disputed` : null,
                          tally.needs_review ? `${tally.needs_review} to review` : null,
                          data.claims.length - decidedCount > 0
                            ? `${data.claims.length - decidedCount} undecided`
                            : null,
                        ]
                          .filter(Boolean)
                          .join(" · ")}
                    {saveState === "saving" && " · Saving…"}
                    {saveState === "saved" && " · Saved"}
                    {saveState === "error" && " · Could not save — changes will retry on next edit"}
                  </p>
                )}
              </div>
              <div className="relative">
              <ul id="oc-evidence-claims" className="space-y-3">
                {(evidenceCollapsed
                  ? data.claims.slice(0, EVIDENCE_PREVIEW_COUNT)
                  : data.claims
                ).map((c) => {
                  const cites = c.fact_ids
                    .map((id) => resolveCite(data.packet, id))
                    .filter((x): x is Cite => x !== null);
                  return (
                    <li key={c.id} className="text-[13px] text-oo-ink">
                      <span>{c.text}</span>{" "}
                      <span className="inline-flex flex-wrap gap-1 align-middle">
                        {cites.map((cite) => (
                          <CitationChip key={`${c.id}-${cite.id}`} cite={cite} />
                        ))}
                      </span>
                      {canSignOff && (
                        <DispositionControls
                          claimId={c.id}
                          value={disp[c.id]}
                          commentOpen={Boolean(commentOpen[c.id])}
                          onStatus={(s) => setClaimStatus(c.id, s)}
                          onComment={(text) => setClaimComment(c.id, text)}
                          onToggleComment={() =>
                            setCommentOpen((prev) => ({ ...prev, [c.id]: !prev[c.id] }))
                          }
                        />
                      )}
                    </li>
                  );
                })}
              </ul>
              {evidenceCollapsed && (
                <div
                  aria-hidden
                  className="pointer-events-none absolute inset-x-0 bottom-0 h-10 bg-gradient-to-b from-transparent to-white"
                />
              )}
              </div>
              {evidenceCollapsed && (
                <button
                  type="button"
                  aria-expanded={false}
                  aria-controls="oc-evidence-claims"
                  onClick={() => {
                    setEvidenceExpanded(true);
                    trackEvent("evidence_expand");
                  }}
                  className="mt-2 inline-flex items-center gap-1.5 rounded-oo border border-[#cfd6f5] bg-[#eef1fb] px-4 py-2 text-[13px] font-semibold text-oo-blue transition-colors hover:bg-[#e3e8f8]"
                >
                  Show all {data.claims.length} evidence statements
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-3.5 h-3.5" aria-hidden>
                    <path fillRule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clipRule="evenodd" />
                  </svg>
                </button>
              )}
              {evidenceCollapsible && !evidenceCollapsed && (
                <button
                  type="button"
                  aria-expanded={true}
                  aria-controls="oc-evidence-claims"
                  onClick={() => setEvidenceExpanded(false)}
                  className="mt-2 text-[12px] font-medium text-oo-blue underline underline-offset-2 hover:text-oo-burst"
                >
                  Collapse evidence
                </button>
              )}
              {cached && data.claims.length > 0 && (
                <p className="mt-2 text-[11px] text-oo-muted">
                  Sign-off (accept / dispute per statement) is available on live summaries —
                  use &ldquo;Regenerate live&rdquo; below.
                </p>
              )}
            </div>
          )}

          {data.packet.gaps.length > 0 && (
            <div className="mt-4 bg-amber-50/60 border border-amber-200 rounded-oo px-3 py-2">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-amber-900 mb-1">
                Not verified in this check
              </p>
              <ul className="list-disc pl-5 space-y-0.5">
                {data.packet.gaps.map((g) => (
                  <li key={g.id} className="text-[12px] text-amber-900">
                    {g.statement}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {data.limitations.length > 0 && (
            <div className="mt-4">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-oo-muted mb-1">
                Limitations
              </p>
              <ul className="list-disc pl-5 space-y-0.5">
                {data.limitations.map((l, i) => (
                  <li key={i} className="text-[12px] text-oo-muted">{l}</li>
                ))}
              </ul>
            </div>
          )}

          {!data.validation_ok && (
            <p className="mt-3 text-[12px] text-amber-800 bg-amber-50 border border-amber-200 rounded-oo px-3 py-2">
              {data.dropped_claims.length} statement
              {data.dropped_claims.length === 1 ? " was" : "s were"} withheld because they could not be
              tied to a source.
            </p>
          )}

          <p className="mt-4 text-[11px] text-oo-muted border-t border-oo-rule pt-3">
            {cached && (
              <span className="font-medium text-oo-ink">Saved example summary. </span>
            )}
            AI-generated from OpenCheck&rsquo;s data. Every claim is grounded in the cited sources; nothing
            is added beyond what they state. Generated by {data.model} · prompt {data.prompt_version}
            {data.run_id ? <> · run <span className="font-mono">{data.run_id}</span></> : null}.{" "}
            <button type="button" onClick={generate} className="text-oo-blue hover:underline">
              {cached ? "Regenerate live" : "Regenerate"}
            </button>
          </p>
        </div>
      )}
    </section>
  );
}
